before:
  hooks:
    - go mod download
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge'
release:
  prerelease: auto
builds:
  - main: ./cmd
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath